### ISSUE TITLE
avgFinishExcludingDnf error

### ISSUE THREAD

**Issue by melon-person-18** [64Soft/NRatings.Client#1]
Putting avgFinishExcludingDnf in a formula gives an error due to the order in which NRatings replaces variable names with actual values. It will see "avgFinish" and replace it with a number, which will sometimes result in a number with "ExcludingDnf" immediately after it. Easiest fix is to switch the two in the formula variable list so that avgFinishExcludingDnf is first.

**Comment by 64Soft** [comment]
Thanks for the finding and the solution. Has now been fixed
