### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by 64Soft** [64Soft/NRatings.Client#10]
Last night when I tried to run NRatings, it said I had to authenticate myself, so I made an account and was sent a link to confirm my email, but now all I get when loading NRatings real results in this load screen and nothing happens.
![bandicam 2020-12-27 11-58-45-695](https://user-images.githubusercontent.com/76636255/103175802-c7a95b00-483a-11eb-802a-dbcf462743cd.jpg)

_Originally posted by @BlaiseZebrataur in https://github.com/64Soft/NRatings.Client/issues/2#issuecomment-751491191_

**Comment by 64Soft** [comment]
Please see if v5.1.1 fixes the issue

**Comment by BlaiseZebrataur** [comment]
Nope it doesn't work.

When I go under tools to login in I get the same pop up message saying it's authenticating with the word "ok" underneath, but it does nothing and I've been waiting five minutes.

I do have an account, I signed up for it and it verified my email and gave me a check mark, so I don't know what's going on.

**Comment by 64Soft** [comment]
Yes in the meantime I've been able to reproduce the error on a Win7 VM.

Working on a fix... Will be out soon.

Op di 29 dec. 2020 20:30 schreef BlaiseZebrataur <notifications@github.com>:

**Comment by 64Soft** [comment]
v5.1.2 is now released which uses the Edge WebView2 component (you will be prompted to install it in NRatings if you don't have it). This should hopefully fix it for all users across all OS's. Let me know if it works.

ps: if you're having trouble installing the WebView2 component from within NRatings, please install it directly from this link: https://go.microsoft.com/fwlink/p/?LinkId=2124703

**Comment by BlaiseZebrataur** [comment]
> v5.1.2 is now released which uses the Edge WebView2 component (you will be prompted to install it in NRatings if you don't have it). This should hopefully fix it for all users across all OS's. Let me know if it works.
> 
> ps: if you're having trouble installing the WebView2 component from within NRatings, please install it directly from this link: https://go.microsoft.com/fwlink/p/?LinkId=2124703

Yep that did it, NRatings back to working with no problems. Thank you!
