### ISSUE TITLE
Email verification issue

### ISSUE THREAD

**Issue by jgf18eighteen** [64Soft/NRatings.Client#13]
So I installed the newest version of NRatings to see if the authentication issue had been fixed, but when I logged into my account, I was told that I needed to verify my email address. I've taken a screenshot which you can see below:
![2021-01-05](https://user-images.githubusercontent.com/76660143/103615091-11eab480-4f7e-11eb-89f7-39d51980be41.png)
My email address had already been verified at this point, so I went to see if I could re-verify it. It wouldn't allow me to do so, which is understandable given I had already verified it prior to the new update. I uninstalled NRatings entirely from my PC and redownloaded it, thinking that a fresh install would allow me to enter my login details again. However, when I attempted to do so, the same message came up. I'm not sure if I've done something wrong or if there are still issues, but any help would be greatly appreciated.

**Comment by 64Soft** [comment]
Hi,

try going to Tools / Options / Log Out / Log In. You will get the
authentication screen again, from where you can do a password recovery
process. That should help unblock everything. If it still doesn't work
please let me know.

Mathieu

**Comment by jgf18eighteen** [comment]
Knew it was something on my end, everything's good now. Thanks so much for your help my guy.

**Comment by jgf18eighteen** [comment]
Knew it was something on my end, everything's good now. Thanks so much for your help my guy.
