### ISSUE TITLE
Import Ratings from Real Life Data Button Not Working

### ISSUE THREAD

**Issue by CowFeeder18** [64Soft/NRatings.Client#14]
Whenever I click Import Ratings from Real Life Data, nothing happens.

**Comment by 64Soft** [comment]
Everything working fine on my side regarding the login and Import from Real Life Data. Try going to tools - options - login. If you are already logged in, the log out button should be displayed. Try logging out, close NRatings, reopen, and re-log in.

If it still doesn't work, please mention your Windows version.

**Comment by CowFeeder18** [comment]
I am not currently logged in, as I am trying to log in. I am using win10 1909.

**Comment by OttoTheFuzzBall** [comment]
I was in the middle of using the program and suddenly the button stopped doing anything, it now says I am not logged in and when I click log in nothing happens. Windows 10 Version 2004

**Comment by 64Soft** [comment]
I think I've found the issue. Will post an update in the next coming days, along with the update of the new data of the 2021 season

**Comment by 64Soft** [comment]
v5.1.3 has been released which should fix this. Please check if that solves the issue. If you get to the real-life data data screen but don't see any data, please log out and log back in (from the tools/options menu).
