### ISSUE TITLE
Missing Series?

### ISSUE THREAD

**Issue by BlaiseZebrataur** [64Soft/NRatings.Client#17]
I just wanted to point out that since the newest update, not all of the former series that NRatings had are now missing, like IROC, Convertible Series, IndyCar, Whelen Southern Modified and a few more if I remember correctly.

Just wanted to ask if this is a glitch or if you removed them.
![bandicam 2021-02-28 22-05-12-959](https://user-images.githubusercontent.com/76636255/109447489-c995c300-7a11-11eb-86b9-3297d6c62019.jpg)

**Comment by 64Soft** [comment]
Correct, currently they are not available as I had to reparse the whole data for all series, but these you mention had some slight differences which meant the code did not parse them correctly. I need to make some adjustment for these. I might be able to do it in the next few days.

**Comment by epicninjali** [comment]
Is adding a series something anyone can just add themselves maybe via a tutorial? I also would like to see the NASCAR Mexico and NASCAR Whelen Euro Series.

**Comment by ccoco6126** [comment]
Any Update in the Indycar series

**Comment by 64Soft** [comment]
> Is adding a series something anyone can just add themselves maybe via a tutorial? I also would like to see the NASCAR Mexico and NASCAR Whelen Euro Series.

Not really no, the data is fetched from a backend system

**Comment by BlaiseZebrataur** [comment]
It's been well over six months, are you getting any closer in bringing back the IndyCar, Convertible and IROC results as well as the others that was on here before your update?

**Comment by 64Soft** [comment]
Not yet, I'm doing this in my free time and things have been pretty hectic the last few months. It takes time to do it right. Can't give you an ETA sorry.

**Comment by ninjatfp** [comment]
please add the indy& cart  car series data

**Comment by MadDogMatt** [comment]
Hey @64Soft, I would like to help you with adding these series to NRatings. Please contact me.
