### ISSUE TITLE
NRatings stopped working on my Windows7 PC yesterday.

### ISSUE THREAD

**Issue by JRFranklin62** [64Soft/NRatings.Client#23]
As the subject line states, I cannot seem to get the app to open anymore.  I've never had an issue before and have the most current version of the program (v5.1.6).  Will this be fixed soon?

**Comment by 64Soft** [comment]
Do you get any error messages?

The thing that changed in 5.1.6 is that now the local browser is used for
the authentication part instead of the embedded browser (WebView2) because
the latter doesn't work anymore with Google Authentication since a recent
change on their side.
In order for the authentication mechanism to work with the local browser, a
specific port (64646) on your PC is opened on startup of NRatings to listen
to incoming authentication callbacks. In 99.9% of the cases this port is
probably free but maybe you'll need to check if you have any other specific
application running on your PC that is using this port. Try doing a port
scan on your PC to see which ports are in use.

Let me know your findings

**Comment by JRFranklin62** [comment]
Here is the error message that I get when I try to open NRatings.

[image: Image2.jpg]
It doesn't appear that my PC has any ports or any way to add them.

[image: Image1.jpg]
Is there a way for me to resolve this?

Thanks,
J.R. Franklin

**Comment by 64Soft** [comment]
Cant seem to see the images you posted

**Comment by JRFranklin62** [comment]
They are jpgs.  Let me try this again.  I'll attach them instead of
inserting them into the email.

Hopefully, you;ll be able to open them now and see them.

Thank,
J.R.

**Comment by 64Soft** [comment]
Nope they are still not attached. Please instead of going via email, attach them directly in the Github issue thread: https://github.com/64Soft/NRatings.Client/issues/23

**Comment by JRFranklin62** [comment]
Here is the error message I am getting:
![Image2](https://user-images.githubusercontent.com/89108271/129982999-1a787a06-3f8a-4ebb-ad7b-9fe1c41c7563.jpg)

It doesn't appear that my PC has any ports or any way to add them.:
![Image1](https://user-images.githubusercontent.com/89108271/129983037-cde23585-165e-4065-843d-28acc22f175b.jpg)

Is there a way to fix this?

As you may remember, we are the guys from Ground Pounder Designs who provide all of the Whelen Modifieds for NR2003.  So I really need to figure out how to get NRatings working again.  As always, thanks for your awesome ratings tool and for any help you can provide me in getting this working.  I'm not the most PC savvy guy.

J.R. Franklin

**Comment by JRFranklin62** [comment]
Okay.  I posted the pics at the GitHub issue forum.

**Comment by 64Soft** [comment]
Ok thanks now I see them.

Do you get this error the moment you start up NRatings or does it happen when you perform a specific action within NRatings ? Also, you might want to go into Windows Event Viewer and see if you find any errors there in the "Application" or "System" tabs under "Windows Logs" at the timestamp you get the error. If you do, please post the error details.

![image](https://user-images.githubusercontent.com/3592524/130020145-3998c7b7-f040-45f6-bbdf-ebdb8afca39f.png)

You could also try to download Advanced-Port Scanner https://www.advanced-port-scanner.com/ and with **NRatings closed**, do a scan of "localhost" of "All TCP ports" and see in the resulting list on the right if port 64646 is mentioned there. If it is, it means the port is in use by some other app and we'll need to investigate further to find out which one.

![image](https://user-images.githubusercontent.com/3592524/130020533-c0bb65ab-cd8c-4677-a50d-fd0bfbd32c23.png)

In the meantime, I'll try to start up a Windows 7 VM and see if I can reproduce the error. I do my development and testing on Windows 10.

**Comment by JRFranklin62** [comment]
I get that message immediately after clicking on the shortcut icon.

**Comment by 64Soft** [comment]
v5.1.7 is being released shortly and it will tell you on startup of NRatings if the required port is already occupied by another app. If that is the case, you'll need to investigate which one. You can use above mentioned port scanner or TCPView for that (https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview)
