### ISSUE TITLE
FIXED* Unable to Login; Service May Be Down Since Update?

### ISSUE THREAD

**Issue by KBMfan** [64Soft/NRatings.Client#29]
Nratings runs normally up until the point it's time to "import real life data," when the user is flooded with error messages and is then led to a login page that does not function properly as it doesn't log the user in, but says it did. Never had this issue before with the software. 1/2/2022

**Comment by KBMfan** [comment]
UPDATE: I've got the software functioning properly now by deleting the usersettings file in documents as suggested in another thread but the error messages still continue. I'd prefer to get rid of them but at least the program runs properly now.

**Comment by 64Soft** [comment]
Are you still getting these other error message you speak of ? If so, could you tell me exactly what they say or post a screenshot. Or if this is solved, please let me know too so I can close this issue. Thanks.

**Comment by KBMfan** [comment]
Hi Mathieu hopefully this message gets to you. Sorry it took me so long to get back to you.

Thanks for reaching out, but no I am no longer receiving any error messages as of last night. The program runs perfectly normal now so whatever fix you guys did seemed to do the trick. You could probably close the ticket if you haven't already. I'll be making another donation soon due to your kindness. Have a great day!
________________________________
