### ISSUE TITLE
duplicate drivers in ratings calculation

### ISSUE THREAD

**Issue by melon-person-18** [64Soft/NRatings.Client#3]
When calculating ratings, it seems that something changed for races around July 6, 2017 that causes every driver with a period in their name (who participated in selected races both before and after that date) to show up twice. The first instance of each driver will have ratings and statistics from every selected race before 7/6/2017, and the second will have ratings and statistics from every selected race on or after that date. This "split" happens in that exact spot for every driver in every series who has a "." in their name (such as A.J. Allmendinger or Martin Truex, Jr.).

This has the effect of significantly dropping ratings for affected cars when using a formula that favors drivers who run more races. For example, if you're rating cars based on just 2017, Martin Truex, Jr. will most likely be rated around 20th place due to the program seeing him as having missed half the season (only one instance can be applied to a car file), despite winning the championship.

(used Ethone's formula as an example)
![nratings_ddbug_1](https://user-images.githubusercontent.com/75181296/100930675-6a2e2280-34b7-11eb-8ec9-e04614adccb4.png)
![nratings_ddbug_2](https://user-images.githubusercontent.com/75181296/100929432-a1033900-34b5-11eb-9510-88f2a410a4b3.png)

It's also worth noting that D.J. Kennington has *another* split near the same date (July 6) in 2018, which causes him to actually show up *three* times if you get ratings from both 2017 and 2018. Weirdly, only Kennington has the issue in 2018 (everyone else only has it in 2017), and he only has it in the Cup series.

**Comment by 64Soft** [comment]
Wow, you dug deep there, impressive ! I'll have a look in the database later to see if indeed the drivers exist twice and if they do, what the cause could be

**Comment by 64Soft** [comment]
Indeed, at some point around July 2017 racing-reference.info seems to have renamed a lot of their driver identifiers on their website, getting rid of dots. For instance id "Martin_Truex_Jr." became "Martin_Truex_Jr". This resulted in the parsing logic considering this driver as a new one, hence creating it again in the database.

Will try to write some scripts to correct the data without having to reparse everything.

**Comment by melon-person-18** [comment]
Would it work if you set it to remove underscores and periods when getting the secondary IDs, or does the problem run a bit deeper than that?

**Comment by 64Soft** [comment]
Could be an option but I'll need to check if two actual separate drivers wouldn't collide in terms of ID in that case... In theory not, but you never know

**Comment by 64Soft** [comment]
The data has now been completely reparsed with additional checks and there should be no duplicate drivers anymore
