### ISSUE TITLE
Car Mapping Method by Name/Number only miscalculation if name has multiple numbers and vice versa

### ISSUE THREAD

**Issue by ai-line-mod** [64Soft/NRatings.Client#30]
This issue was raised in #26. If Name/Number mapping method is chosen and a name/number competes under multiple numbers/names, NRatings averages the averages of name/number combination. For example, Jeff Burton in 2004 drove 22 races in # 99 and 14 races in # 30 for an overall season average finish of 18.7 and average start of 23.7 (https://www.racing-reference.info/driver-season-stats/burtoje01/2004/W/). However NRatings suggests that the average finish is 18.1 average start 23.6. Nratings is taking an average of an average to determine these values. In other words, in the # 99 car, Burton had an average finish/start of 18.9/23.8, and in the # 30 car 15.4/22.9. Averaging those two values results in an average finish/start of 18.1 and 23.6 - the same values NRatings uses for the driver Jeff Burton when the mapping method Name Only is selected.

Following the logic to determine where NRatings is making this error is difficult to do without real life values, but it appears the issue is occurring in the real data processor (https://github.com/64Soft/NRatings.Client/blob/main/src/NRatings.Client/Business/RealDataProcessor.cs) during the creation of the stats list, approximately line 500 for the driver only method. The code for generating that list is different from the above code for mapping by both name and number above, which seems to work correctly. The mapping by number only below follows the same logic as mapping by name only, and therefore should experience this same issue.

**Comment by 64Soft** [comment]
@ai-line-mod thanks for your investigation. I unfortunately don't have much time at the moment to look into this, so my question to you is would you feel comfortable to set up a develop environment on your side to try and fix the issue ? I can set you up with the connection to the data server to connect it with your dev environment.

**Comment by ai-line-mod** [comment]
@64Soft Yes most definitely! I just set up the environment on my end. What do you need in order to connect it to the data server?

**Comment by 64Soft** [comment]
@ai-line-mod drop me an email at mathieu@64soft.eu so I can send you the details by email
