### ISSUE TITLE
No Race Results Parsing for Any Series Post July '22 Pocono Cup Race

### ISSUE THREAD

**Issue by KBMfan** [64Soft/NRatings.Client#38]
Same issue as two weeks ago just different time period(s) this time. Just letting you know if you aren't already aware of the problem. Hope there isn't some sort of glitch going on during the parsing process again.

**Comment by 64Soft** [comment]
Should be fine now. Parsing is automated but I have to trigger it manually. I was on leave/holiday the last few days and didn't get to trigger it recently. Done now. Automtaing the trigger is on my todo list :-)

**Comment by KBMfan** [comment]
Totally understandable man thanks for all your work and help keeping NR2003 alive!!
