### ISSUE TITLE
Port 64646

### ISSUE THREAD

**Issue by DiamondAviation** [64Soft/NRatings.Client#41]
Hey, I recently installed Windows 11, and in the process of reinstalling programs. I installed Nratings, and on launch I get an error referring to port 64646 being occupied, but when I check TCPview, only thing that is dealing with this port is the SYSTEM listening, and I don't any other programs using the port. This is also preventing me from logging in. Thanks for the help. 
![image](https://user-images.githubusercontent.com/115908240/196014742-69c7c8fa-79d7-4caf-8750-30ead58c34d5.png)
![image](https://user-images.githubusercontent.com/115908240/196014750-3f085aa0-baee-4236-92e5-09aaaeadda13.png)
#

**Comment by 64Soft** [comment]
Hi, can you please try running NRatings after a clean Windows boot, without opening much other applications or browser. Could be that a browser session has taken up port 64646 (which is in the ephemeral port range so Windows might possibly allocate this to a random outgoing session).

If that still doesn't help, let me know.
