### ISSUE TITLE
Race Results Not Parsing for Any Series in 2023 So Far

### ISSUE THREAD

**Issue by KBMfan** [64Soft/NRatings.Client#45]
Figured I would make you guys aware as your software is a crucial part of keeping NR2003 up to date! I still think an auto parsing process would fix these delays if you get around to it. Here's to the 2023 NASCAR season and thanks for your work!

**Comment by 64Soft** [comment]
Apologies for the delay in getting the 2023 season underway, just got back home in Europe this weekend from an amazing Florida trip, including attending the Daytona 500 :-). 2023 is now available. You're right about the automated parsing and it's been on my todo list for a long time and long overdue. I recently found out about a technology to assist me in hopefully easily achieving this automation task without too much coding, so I will try to look into it in the upcoming days.
