### ISSUE TITLE
Parsing Issue with LV1 2023 Cup Race (All Other Series Updated Successfully)

### ISSUE THREAD

**Issue by KBMfan** [64Soft/NRatings.Client#46]
Hey 64! Just figured I would pass along the word if you aren't aware of the issue already. Xfinity and Trucks were parsed successfully based on what I am seeing, but Cup is missing the Vegas 1 race. No rush, just wanted to say something. 

I know I say it a lot but thanks (again) so much for your work! So many people in this community appreciate it, but I feel like I come across as a downer on here lol. It's not intentional man. If only there was a "compliment" section haha. Keep it up! :) Cheers!

**Comment by 64Soft** [comment]
I know, but at the time of writing season-stats - Racing-Reference
<https://www.racing-reference.info/season-stats/2023/W/> doesn't contain
the results for the Cup Vegas race yet, that's why.

**Comment by KBMfan** [comment]
Ah okay gotchya man! Nothing you can do on that one lol. I will be sure to check that site from now on before creating a post. My bad! Thanks for the quick response. Closing now.
