### ISSUE TITLE
Latest data unable to be loaded

### ISSUE THREAD

**Issue by 64Soft** [64Soft/NRatings.Client#49]
Something changed on the racing-reference.info server that currently stops the parsing logic to function properly, hence no new data can be loaded. I'm aware of it, no need to open another issue.

**Comment by KBMfan** [comment]
Any updates on this by chance?

**Comment by 64Soft** [comment]
Not had the chance yet to thoroughly look into it. Can't give you an ETA at
the moment, sorry

Op wo 14 jun. 2023 00:12 schreef KBMfan ***@***.***>:

**Comment by NCG-Mariner** [comment]
Hi
Is there any progress on this ? 
I'm not concerned about when but more about if 
Is this issue fixable ?
Is NRatings over?

**Comment by 64Soft** [comment]
Yes it parses RR in the backend. I'll have some time in the next few days
to have another look at it and at potential alternatives. Thanks for the
info.

Op di 25 jul. 2023 19:55 schreef Nick ***@***.***>:

**Comment by KBMfan** [comment]
I'm still holding out hope whatever this issue is will be fixable. If NRatings goes down it'll be useful for historical seasons, but it would be a gigantic blow to the up-to-date NR2003 community for sure. I'm sure there are others in this community who can and will help you, 64, if you yourself don't have the time personally. This program is almost as important as having the game itself, or at least it was. Hope we get some good news sometime soon because trying to modify the ratings myself (and keeping them current) is a nightmare without NRatings lol.

**Comment by scnrfrq** [comment]
I really miss it this season. Any updates on progress?

**Comment by 64Soft** [comment]
I found an api (https://feed.nascar.com/swagger/ui/index) that supposedly contains all NASCAR results and reached out to the NASCAR helpdesk if there's a chance to obtain access to it, but they told me I had to write a letter (welcome to 2023) to their headquarters. Not going to happen. A possible other track I'm investigating is indeed as mentioned by @Nicky198 using data from https://www.thethirdturn.com/wiki/The_Third_Turn instead of racing-reference.info. I reached out to them and they had no objections in me using their data for the purpose of NRatings. Two challenges however:

1. It will take a substantial amount of work to adapt the code to get the data from their site instead of RR, and I'm still trying to figure out the most effective way to do it.
2. Loopdata and pitstopdata for NASCAR races don't seem to be part of their dataset, so any formulas relying on this data will no longer work and most likely need to be rewritten.

So for the time being I cannot give you an ETA unfortunately.

**Comment by ai-line-mod** [comment]
Happy to help draft a letter if that would be useful! I'm sure others in the community could assist in letter writing as necessary. Otherwise, here for other testing and support!

**Comment by scnrfrq** [comment]
Any updates?

**Comment by LetMeSurvive** [comment]
I saw this website and was thinking this could be a potential option for nascar results (pending how hard it would be to adapt the code). I'm using it while nratings is down to help make at least somewhat realistic ratings. Of course, if progress has already been made based on a different site then that's awesome too!
https://www.lapraptor.com/dashboard/

**Comment by 64Soft** [comment]
sorry, no real updates on the matter due to lack of time lately. If anybody knows a .NET developer in the NR2003 community that potentially feels up to the task, please let them contact me to see if we can sort something out.

**Comment by nschwiet** [comment]
> sorry, no real updates on the matter due to lack of time lately. If anybody knows a .NET developer in the NR2003 community that potentially feels up to the task, please let them contact me to see if we can sort something out.

I can give my hand a try. I'm not a developer, but I'm able to follow the code and make adjustments. I already have a fork of the latest code.

**Comment by ai-line-mod** [comment]
> sorry, no real updates on the matter due to lack of time lately. If anybody knows a .NET developer in the NR2003 community that potentially feels up to the task, please let them contact me to see if we can sort something out.

I can try my hand at the code. I'm not a developer, but I have the latest fork of the code and can follow and make adjustments.

**Comment by scnrfrq** [comment]
Has anyone been able to start on this?

**Comment by KBMfan** [comment]
> Has anyone been able to start on this?

Doesn’t sound like it. “ai-line-mod” offered to take a shot at it (and I trust him, personally, since he’s developed a ratings formula for NRatings already, he has some knowledge of the coding from the sound of it), but Mathieu either hasn’t seen it or just didn’t reply. 

I’m kind of frustrated by it honestly. Why go through the trouble of creating this great thing to let it die like this? Other people are willing to help you. Consider it at the very least. They mean well.

**Comment by ai-line-mod** [comment]
I have not heard anything from 64soft yet. 

Also, I wouldn't be so critical. It is fantastic that this tool exists in the first place, and without it, I'm not sure I'd still be playing NR2003 myself. My interest in the data is from the Winston cup era, so roughly late 70s through 2003, which the program still serves just fine. However I know others want more contemporary data, so I am willing to help to keep the community alive.

That being said, I'm pretty sure that this backend change to RR will require a rewrite to at least half the program, a non-trivial process that will take time.

**Comment by scnrfrq** [comment]
Daytona will be here before we know it. Is there anything the community can do to get NRatings working again? If not, is there anyone who can come up with a good alternative? So far I haven't found one, and I'm not knowledgeable enough to work on one.

**Comment by 64Soft** [comment]
Apologies for the lack of information lately but this holiday period is the first time in months I've had the opportunity to work on NRatings. A solution is (most likely) in the making and you should have more news in the upcoming days. Meanwhile I wish you all happy end of year festivities.

**Comment by scnrfrq** [comment]
That's great news! I'm sure everyone who uses it really appreciates your efforts. It really says how valuable it is when there are just no good alternatives.

**Comment by 64Soft** [comment]
Took some sweat and tears but this has now been fixed. All the 2023 data is available, and let's hope going forward there won't be too much issues next season... Enjoy, and happy New Year (almost)

**Comment by KBMfan** [comment]
> Took some sweat and tears but this has now been fixed. All the 2023 data is available, and let's hope going forward there won't be too much issues next season... Enjoy, and happy New Year (almost)

Thank you so much for you hard work man! You have made something that's damn near essential in keeping the best offline racing sim alive. I'm ecstatic to see that it will live on even longer now. Have a Happy New Year everyone!
