### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by brain20lane** [64Soft/NRatings.Client#8]
Glad you are keeping NRatings alive. However, I'm having an issue with logging in to the software after the update. I get an authentication screen that has the word OK written on it but nothing happens and I'm not able to login. I can't get back to the login screen to try to login via a different method. 

Any way to remove the login requirement?

![image](https://user-images.githubusercontent.com/76693926/103220027-75b91180-48dc-11eb-9fa1-db6155bc4397.png)

**Comment by 64Soft** [comment]
Hi,

sorry to hear about your issues. Unfortunately I cannot take the login
requirement away, it's too much of a legal risk to leave the backend API
wide open. But several users are reporting the same issue and I'm looking
for a solution so please stay tuned.

Looks like most of them are still on Windows 7 and by the look of your
screenshot this could also be the case for you.

When I find something I'll post an updated version.

Mathieu

**Comment by brain20lane** [comment]
Hi Mathieu,

Thanks for the quick response. Yeah, Windows 7 being an issue makes sense. I need to update it anyway. 

Brian
